service: test

frameworkVersion: '2'

plugins:
  - serverless-offline
  - serverless-bundle	

custom:
  bundle:
    sourcemaps: true 
    caching: false
    stats: false
    linting: false
    forceExclude:
      - _http_common

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  create:
    handler: handler.create
    events:
      - http:
          path: /users
          method: post
          cors: true
          request:
           schema:
             application/json: ${file(./src/schemas/createUser.json)}

  get:
    handler: handler.get
    events:
      - http:
          path: /users
          method: get
          cors: true

  update:
    handler: handler.update
    events:
      - http:
          path: /users
          method: patch
          cors: true
          request:
           schema:
             application/json: ${file(./src/schemas/updateUser.json)}

  remove:
    handler: handler.remove
    events:
      - http:
          path: /users
          method: delete
          cors: true